syntax = "proto3";

option csharp_namespace = "F1.TelemetryAnalytics.Service.Grpc";

package telemetryanalytics;

service TelemetryAnalytics {
  rpc GetTyreStintStrategy (TyreStintStrategyRequest) returns (TyreStintStrategyResponse);
  rpc GetDriverLapTelemetry (DriverLapTelemetryRequest) returns (DriverLapTelemetryResponse);
}

message TyreStintStrategyRequest {
  string session_id = 1;
}

message TyreStintStrategyResponse {
  string session_id = 1;
  int32 total_laps = 2;
  repeated TyreStintDriver drivers = 3;
}

message TyreStintDriver {
  int32 driver_number = 1;
  string driver_name = 2;
  string team_name = 3;
  string team_color = 4;
  int32 grid_position = 5;
  int32 position = 6;
  repeated TyreStint stints = 7;
}

message TyreStint {
  int32 stint_number = 1;
  string compound = 2;
  bool tyre_is_new = 3;
  int32 start_lap = 4;
  int32 end_lap = 5;
  int32 lap_count = 6;
}

message DriverLapTelemetryRequest {
  string session_id = 1;
  int32 driver_number = 2;
  int32 lap_number = 3;
  repeated string requested_metrics = 4;
}

message DriverLapTelemetryResponse {
  string session_id = 1;
  int32 driver_number = 2;
  int32 lap_number = 3;
  repeated string returned_metrics = 4;
  repeated LiveTelemetrySample samples = 5;
}

message LiveTelemetrySample {
  string session_id = 1;
  int32 driver_number = 2;
  int32 lap_number = 3;
  int32 stint_number = 4;
  int32 sample_index = 5;
  string timestamp = 6;
  int32 speed = 7;
  int32 rpm = 8;
  int32 throttle_pct = 9;
  int32 raw_throttle = 10;
  double brake_pct = 11;
  int32 raw_brake = 12;
  int32 gear = 13;
  bool drs_enabled = 14;
}
